name: 'Repo Creation'
on:
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''
      repo-Description:
        description: 'Description of repo'
        required: true
        default: ''

jobs:
  test:
    env:
      ORG_TOKEN: ${{ secrets.REPO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Repo
        id: create-repo
        uses: ./
        with:
         # zipPath: 'examples/test.zip'
         # possible to add files as a inital commit
          repoName: '${{ github.event.inputs.repo-name }}'
         # repoOrg: 'defencedigital'
          repoDescription: '${{ github.event.inputs.repo-description }}'
          repoVisibility: 'private'
          securityToken: ${{ secrets.REPO_TOKEN }}
          #envsToRepoSecrets: ORG_TOKEN
      - name: Get the repo URL
        run: echo "The repo URL is ${{ steps.create-repo.outputs.repoUrl }}"
